### PR TITLE
🚧  (db queries) update weekly and monthly category budgets

### PR DESCRIPTION
**Pull request by SeePeeYou**

### CODE REVIEW

**Comment by druha4087** [comment]
Gabe just made a PR, please make sure your branch is updated before I can approve it

**Review by Grobbies26 — CHANGES_REQUESTED** [review]
Does this work

**Comment by SeePeeYou** [comment]
what do you mean?

**Comment by Grobbies26** [comment]
How do you know that it works, how did you test it

**Comment by Grobbies26** [comment]
Alright I understand how you tested it now

**Review by Grobbies26 — APPROVED** [review]

**Pull request merged**
